django_project_template/urls.py
from django.conf.urls import *
from django.contrib import admin
from students.views import students, groups, journal, exams, contact_admin
from .settings import MEDIA_ROOT, DEBUG
from django.conf import settings
from django.views.static import serve
from django.views.i18n import javascript_catalog
from django.views.i18n import JavaScriptCatalog
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    # Students urls
    url(r'^$', students.students_list, name='home'),
    url(r'^students/add/$', students.students_add, name='students_add'),
    url(r'^students/(?P<pk>\d+)/edit/$', students.StudentUpdateView.as_view(), name='students_edit'),
    url(r'^students/(?P<pk>\d+)/delete/$', students.StudentDeleteView.as_view(), name='students_delete'),

    # Groups urls
    url(r'^groups/$', groups.groups_list, name='groups'),
    url(r'^groups/add/$', login_required(groups.groups_add), name='groups_add'),
    url(r'^groups/(?P<gid>\d+)/edit/$', groups.groups_edit, name='groups_edit'),
    url(r'^groups/(?P<gid>\d+)/delete/$', groups.groups_delete, name='groups_delete'),

    # Journal urls
    url(r'^journal/(?P<pk>\d+)?/?$', journal.JournalView.as_view(), name='journal'),

    # Exams urls
    url(r'^exams/$', exams.exams_list, name='exams'),

    # Contact_admin url
    url(r'^contact-admin/$', contact_admin.contact_admin, name='contact_admin'),

    url(r'^jsi18n\.js$', JavaScriptCatalog.as_view(packages=['students']), name='javascript-catalog'),

    url(r'^admin/', include(admin.site.urls)),

    # User Related urls
    url(r'^users/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name='profile'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
        name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls',
        namespace='users')),

    # Social Auth Related urls
    url('^social/', include('social_django.urls', namespace='social')),
    ]

if settings.DEBUG:
# serve files from media folder
        urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
                        ]

students/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Student(models.Model):

    class Meta(object):
        verbose_name = u"Студент"
        verbose_name_plural = u"Студенти"

    first_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Ім'я")

    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Прізвище")

    middle_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=u"По-батькові",
        default='')

    birthday = models.DateField(
        blank=False,
        verbose_name=u"Дата народження",
        null=True)

    photo = models.ImageField(
        blank=True,
        verbose_name=u"Фото",
        null=True)

    ticket = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Білет")

    student_group = models.ForeignKey('Group',
        verbose_name=u"Група",
        blank=False,
        null=True,
        on_delete=models.PROTECT)

    notes = models.TextField(
        blank=True,
        verbose_name=u"Додаткові нотатки")

    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)


class Group(models.Model):

    class Meta(object):
        verbose_name = u"Група"
        verbose_name_plural = u"Групи"

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Назва")

    leader = models.OneToOneField('Student',
        verbose_name=u"Староста",
        blank=True,
        null=True,
        on_delete=models.SET_NULL)

    notes = models.TextField(
        blank=True,
        verbose_name=u"Додаткові нотатки")

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
        else:
            return u"%s" % (self.title,)

students/models/exams.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from ..models.groups import *


class Ex(models.Model):

    class Meta(object):
        verbose_name = u"Іспит"
        verbose_name_plural = u"Іспити"

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Назва")

    date_time = models.DateTimeField(
        auto_now=False,
        auto_now_add=False,
        blank=False,
        verbose_name=u"Дата і час проведення")

    professor_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=u"Ім'я викладача",
        default='')

    ex_group = models.ForeignKey('Group',
        verbose_name=u"Група",
        blank=False,
        null=True)

    def __unicode__(self):
        return u"%s %s" % (self.title, self.date_time)

students/models/groups.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from ..models.students import *


class Group(models.Model):

    class Meta(object):
        verbose_name = u"Група"
        verbose_name_plural = u"Групи"

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=u"Назва")

    leader = models.OneToOneField('Student',
        verbose_name=u"Староста",
        blank=True,
        null=True,
        on_delete=models.SET_NULL)

    notes = models.TextField(
        blank=True,
        verbose_name=u"Додаткові нотатки")

    def __unicode__(self):
        if self.leader:
            return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
        else:
            return u"%s" % (self.title,)

students/models/students.py
from __future__ import unicode_literals
from django.db import models
from ..models.groups import *
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class Student(models.Model):

    class Meta(object):
        verbose_name = _(u"Student")
        verbose_name_plural = _(u"Students")

    first_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"First Name"))

    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Last Name"))

    middle_name = models.CharField(
        max_length=256,
        blank=True,
        verbose_name=_(u"Middle Name"),
        default='')

    birthday = models.DateField(
        blank=False,
        verbose_name=_(u"Birthday"),
        null=True)

    photo = models.ImageField(
        blank=True,
        verbose_name=_(u"Photo"),
        null=True,)

    ticket = models.CharField(
        max_length=256,
        blank=False,
        verbose_name=_(u"Ticket"))

    student_group = models.ForeignKey('Group',
        verbose_name=_(u"Group"),
        blank=False,
        null=True,
        on_delete=models.PROTECT)

    notes = models.TextField(
        blank=True,
        verbose_name=_(u"Extra Notes"))

    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)

students/views/contact_admin.py
# -*- coding: utf-8 -*-

import logging

from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django_project_template.settings import ADMIN_EMAIL
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.decorators import permission_required


class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        # call original initializator
        super(ContactForm, self).__init__(*args, **kwargs)

        # this helper object allows us to customize form
        self.helper = FormHelper()

        # form tag attributes
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('contact_admin')

        # twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # form buttons
        self.helper.add_input(Submit('send_button', u'Надіслати'))

    from_email = forms.EmailField(
        label=u"Ваша Email адреса")

    subject = forms.CharField(
        label=u"Заголовок листа",
        max_length=128)

    message = forms.CharField(
        label=u"Текст повідомлення",
        max_length=2560,
        widget=forms.Textarea)

@permission_required('auth.add_user')
def contact_admin(request):
    # check if form was posted
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)

        # check whether user data is valid:
        if form.is_valid():
            # send email
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, message, from_email, [ADMIN_EMAIL])
            except Exception:
                message = u'Під час відправки листа виникла непередбачувана ' \
                    u'помилка. Спробуйте скористатись даною формою пізніше.'
                logger = logging.getLogger(__name__)
                logger.exception(message)
            else:
                message = u'Повідомлення успішно надіслане!'

            # redirect to same contact page with success message
            return HttpResponseRedirect(
                u'%s?status_message=%s' % (reverse('contact_admin'), message))

    # if there was not POST render blank form
    else:
        form = ContactForm()

    return render(request, 'contact_admin/form.html', {'form': form})

students/views/exams.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from ..models.exams import Ex
from ..util import get_current_group


def exams_list(request):
    current_group = get_current_group(request)

    if current_group:
        exams = Ex.objects.filter(ex_group=current_group)
    else:
        exams = Ex.objects.all()

    order_by = request.GET.get('order_by', '-date')
    if order_by in ('date_time'):
        exams = exams.order_by(order_by)
        if request.GET.get('reverse', '-date') == '1':
            exams = exams.reverse()

    return render(request, 'exams.html', {'exams': exams})

students/views/groups.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from ..models.groups import Group
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from ..util import get_current_group


def groups_list(request):
    current_group = get_current_group(request)

    if current_group:
        groups = Group.objects.filter(pk=current_group.pk)
    else:
        groups = Group.objects.all()

    order_by = request.GET.get('order_by', '')
    if order_by in ('id', 'title', 'leader'):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            groups = groups.reverse()

    paginator = Paginator(groups, 3)
    page = request.GET.get('page')
    try:
        groups = paginator.page(page)
    except PageNotAnInteger:
        groups = paginator.page(1)
    except EmptyPage:
        groups = paginator.page(paginator.num_pages)

    return render(request, 'groups_list.html', {'groups': groups})

def groups_add(request):
    return HttpResponse('<h1>Groups Add Form</h1>')

def groups_edit(request, gid):
    return HttpResponse('<h1>Edit Group %s</h1>' % gid)

def groups_delete(request, gid):
    return HttpResponse('<h1>Delete Group %s</h1>' % gid)

students/views/journal.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.views.generic.base import TemplateView
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr

from django.http import JsonResponse
from django.core.urlresolvers import reverse
from datetime import datetime, date
from ..models.monthjournal import MonthJournal
from ..models.students import Student
from ..util import paginate, get_current_group


class JournalView(TemplateView):
    template_name = 'journal.html'

    def get_context_data(self, **kwargs):
        # get context data from TemplateView class
        context = super(JournalView, self).get_context_data(**kwargs)

        # check if we need to display some specific month
        if self.request.GET.get('month'):
            month = datetime.strptime(self.request.GET['month'], '%Y-%m-%d'
                ).date()
        else:
            # otherwise just displaying current month data
            today = datetime.today()
            month = date(today.year, today.month, 1)

        # calculate current, previous and next month details;
        # we need this for month navigation element in template
        next_month = month + relativedelta(months=1)
        prev_month = month - relativedelta(months=1)
        context['prev_month'] = prev_month.strftime('%Y-%m-%d')
        context['next_month'] = next_month.strftime('%Y-%m-%d')
        context['year'] = month.year
        context['month_verbose'] = month.strftime('%B')

        # we'll use this variable in students pagination
        context['cur_month'] = month.strftime('%Y-%m-%d')

        # prepare variable for template to generate
        # journal table header elements
        myear, mmonth = month.year, month.month
        number_of_days = monthrange(myear, mmonth)[1]
        context['month_header'] = [{'day': d,
            'verbose': day_abbr[weekday(myear, mmonth, d)][:3]}
            for d in range(1, number_of_days+1)]

        # get all students from database, or just one if we need to
        # display journal for one student; also check if we need to
        # filter by group

        current_group = get_current_group(self.request)

        if kwargs.get('pk'):
            queryset = [Student.objects.get(pk=kwargs['pk'])]
        elif current_group:
            queryset = Student.objects.filter(student_group=current_group)
        else:
            queryset = Student.objects.all().order_by('last_name')

        # url to update student presence, for form post
        update_url = reverse('journal')

        # go over all students and collect data about presence
        # during selected month
        students = []
        for student in queryset:
            # try to get journal object by month selected
            # month and current student
            try:
                journal = MonthJournal.objects.get(student=student, date=month)
            except Exception:
                journal = None

            # fill in days presence list for current student
            days = []
            for day in range(1, number_of_days+1):
                days.append({
                    'day': day,
                    'present': journal and getattr(journal, 'present_day%d' %
                        day, False) or False,
                    'date': date(myear, mmonth, day).strftime(
                        '%Y-%m-%d'),
                })

            # prepare metadata for current student
            students.append({
                'fullname': u'%s %s' % (student.last_name, student.first_name),
                'days': days,
                'id': student.id,
                'update_url': update_url,
            })

        # apply pagination, 10 students per page
        context = paginate(students, 10, self.request, context,
            var_name='students')

        # finally return updated context
        # with paginated students
        return context

    def post(self, request, *args, **kwargs):
        data = request.POST

        # prepare student, dates and presence data
        current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
        month = date(current_date.year, current_date.month, 1)
        present = data['present'] and True or False
        student = Student.objects.get(pk=data['pk'])

        # get or create journal object for given student and month
        journal = MonthJournal.objects.get_or_create(student=student,
             date=month)[0]

        # set new presence on journal for given student and save result
        setattr(journal, 'present_day%d' % current_date.day, present)
        journal.save()

        # return success status
        return JsonResponse({'status': 'success'})

students/templates/base.html
{% load i18n %}
{% load static from staticfiles %}


<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Students Accounting Service" %} - {% block meta_title %}{% endblock meta_title %}</title>
    <meta name="description" value="Система Обліку Студентів Навчального Закладу">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href={{ PORTAL_URL }}{% static "css/main.css" %}>
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
    <div class="container">
        <div class="row" id="header">
            <div class="col-xs-6">
              <h1>{% trans "Students Accounting Service" %}</h1>
            </div>

            {% if user.is_authenticated %}
            <div class="col-xs-4" id="group-selector">
                <strong>{% trans "Group" %}:</strong>
               <select>
          <option value="">{% trans "All Students" %}</option>
          {% for group in GROUPS %}
          <option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>
              {{ group.title }}{% if group.leader %}, {{ group.leader }}{% endif %}
          </option>
          {% endfor %}
        </select>
            </div>

        <!-- User's toolbar for authenticated users -->
          <div class="col-xs-2" id="user-toolbar">
            <a href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
            <a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
          </div>

            {% else %}

            <!-- User’s toolbar for anonymous users -->
            <div class="col-xs-6" id="user-toolbar">
                <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">{% trans "via Facebook" %}</a> |
                <a href="{% url "users:auth_login" %}">{% trans "Login" %}</a> |
                <a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
            </div>
            {% endif %}


        </div>
        <div class="row" id="sub-header">
            <div class="col-xs-12">
              <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation"  {% if request.path == '/' %} class="active"{% endif %}>
                      <a href="/">{% trans "Students" %}</a></li>
                  <li role="presentation" {% if '/journal' in request.path %} class="active"{% endif %}>
                      <a href="/journal">{% trans "Journal" %}</a></li>
                  <li role="presentation" {% if '/groups' in request.path %} class="active"{% endif %}>
                      <a href={% url "groups" %}>{% trans "Groups" %}</a></li>
                  <li role="presentation" {% if '/exams' in request.path %} class="active"{% endif %}>
                      <a href={% url "exams" %}>{% trans "Exams" %}</a></li>
                  {% if perms.auth.add_user %}
                  <li role="presentation" {% if '/contact-admin' in request.path %} class="active"{% endif %}>
                      <a href={% url "contact_admin" %}>{% trans "Contact" %}</a></li>
                  {% endif %}
              </ul>
            </div>
        </div>
        <div class="row" id="content-columns">
            <div class="col-xs-12" id="content-column">

              {% block status_message %}
              {% if request.GET.status_message %}
              <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}
              </div>
              {% endif %}
              {% endblock %}

              <h2>{% block title %}{% endblock title %}</h2>

            {% block content %}{% endblock content %}
            </div>
        </div>

        <div class="row" id="footer">
            <div class="col-xs-12">&copy; 2014 {% trans "Students Accounting Service" %}</div>
        </div>
    </div>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
        </div>
        <div class="modal-body"><!-- --></div>
        <div class="modal-footer"><!-- --></div>
      </div>
    </div>
  </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script src="{% static "js/jquery.cookie.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script
            src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js">

    </script>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static "js/main.js" %}"></script>

    {% block extra_js %}{% endblock extra_js %}

</body>
</html>

students/templates/exams.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block meta_title %}Іспити{% endblock meta_title %}
{% block logo %}Сервіс Обліку Студентів{% endblock logo %}
{% block title %}Іспити{% endblock title %}
{% block content %}

              <a class="btn btn-primary" href=#>Додати Іспит</a>

              <table class="table table-hover table-striped">
              {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
                  <thead>
                    <tr>
                        <th><a href="#">№</a></th>
                        <th><a href="#">Назва предмету</a></th>
                        <th>
                            <a href="{% url "exams" %}?order_by=date_time&reverse=''
                                     {% if order_by == 'date_time' and reverse != '1' %}
                                        &amp;reverse=1{% endif %}">Дата і час проведення
                            {% if order_by == 'date_time' and reverse != '1' %}&uarr;
                                {% elif order_by == 'date_time' and reverse == '1' %}&darr;
                                {% endif %}
                            </a>
                        </th>
                        <th><a href="#">Ім'я викладача</a></th>
                        <th><a href="#">Група</a></th>
                        <th>Дії</th>
                    </tr>
                  </thead>
              {% endwith %}
                <tbody>
                    {% for exam in exams %}
                    <tr>
                        <td>{{ exam.id }}</td>
                        <td>{{ exam.title }}</td>
                        <td>{{ exam.date_time }}</td>
                        <td>{{ exam.professor_name }}</td>
                        <td>{{ exam.ex_group.title }}</td>
                        <td>
                            <div class="dropdown">
                              <button class="btn btn-default dropdown-toggle"
                                      type="button" data-toggle="dropdown">Дія
                                  <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Редагувати</a>
                                  </li>
                                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Видалити</a>
                                  </li>
                              </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>


{% endblock content %}
{% block footer %}&copy; 2014 Сервіс Обліку Студентів{% endblock footer %}

students/templates/groups_list.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block meta_title %}Список груп{% endblock meta_title %}
{% block logo %}Сервіс Обліку Студентів{% endblock logo %}
{% block menu %}
    <strong>Група:</strong>
              <select>
                  <option value="">Усі Групи</option>
                  <option value="">МтМ - 22</option>
                  <option value="">МтМ - 21</option>
                  <option value="">МтМ - 20</option>
              </select>
{% endblock menu %}
{% block title %}Групи{% endblock title %}
{% block content %}

              <a class="btn btn-primary" href={% url "groups_add" %}>Додати Групу</a>

              <table class="table table-hover table-striped">
                {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
                <thead>
                    <tr>
                        <th>
                            <a href="{% url "groups" %}?order_by=id&reverse=''
                                     {% if order_by == 'id' and reverse != '1' %}
                                        &amp;reverse=1{% endif %}">#
                                {% if order_by == 'id' and reverse != '1' %}&uarr;
                                {% elif order_by == 'id' and reverse == '1' %}&darr;
                                {% endif %}
                            </a>
                        </th>
                        <th>
                            <a href="{% url "groups" %}?order_by=title&reverse=''
                                     {% if order_by == 'title' and reverse != '1' %}
                                        &amp;reverse=1{% endif %}">Назва
                                {% if order_by == 'title' and reverse != '1' %}&uarr;
                                {% elif order_by == 'title' and reverse == '1' %}&darr;
                                {% endif %}
                            </a>
                        </th>
                        <th><a href="{% url "groups" %}?order_by=leader&reverse=''
                                     {% if order_by == 'leader' and reverse != '1' %}
                                        &amp;reverse=1{% endif %}">Староста
                                {% if order_by == 'leader' and reverse != '1' %}&uarr;
                                {% elif order_by == 'leader' and reverse == '1' %}&darr;
                                {% endif %}
                            </a>
                        </th>
                        <th>Дії</th>
                    </tr>
                </thead>
                {% endwith %}
                <tbody>
                    {% for group in groups %}
                    <tr>
                        <td>{{ group.id }}</td>
                        <td><a title="Редагувати" href={% url "groups_edit" group.id %}>{{ group.title }}</a></td>
                        <td>{% if group.leader %}<a title="Редагувати" href={% url "students_edit" group.leader.id %}>
                            {{ group.leader }}</a>{% endif %}</td>
                        <td>
                            <div class="dropdown">
                              <button class="btn btn-default dropdown-toggle"
                                      type="button" data-toggle="dropdown">Дія
                                  <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                  <li role="presentation">
                                      <a role="menuitem" tabindex="-1" href={% url "groups_edit" group.id %}>Редагувати</a>
                                  </li>
                                  <li role="presentation">
                                      <a role="menuitem" tabindex="-1" href={% url "groups_delete" group.id %}>Видалити</a>
                                  </li>
                              </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>

    {% if groups.has_other_pages %}
    {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
    <nav>
        <ul class="pagination">
        <li>
            <a href="{% url "groups" %}?page=1&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">&laquo;</a>
        </li>
    {% for p in groups.paginator.page_range %}
        <li {% if groups.number == p %}class="active"{% endif %}>
            <a href="{% url "groups" %}?page={{ p }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">{{ p }}
            </a>
        </li>
    {% endfor %}
        <li>
            <a href="{% url "groups" %}?page={{ groups.paginator.num_pages}}&amp;
            order_by={{ order_by }}&amp;reverse={{ reverse }}"> &raquo;
            </a>
        </li>
        </ul>
    </nav>
    {% endwith %}
    {% endif %}

{% endblock content %}
{% block footer %}&copy; 2014 Сервіс Обліку Груп{% endblock footer %}

students/templates/pagination.html
{% if is_paginated %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav>
  <ul class="pagination">
    <li>
      <a href="?page=1{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">&laquo;</a>
    </li>
    {% for p in paginator.page_range %}
    <li {% if object_list.number == p %}class="active"{% endif %}>
      <a href="?page={{ p }}{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">{{ p }}</a>
    </li>
    {% endfor %}
    <li>
      <a href="?page={{ paginator.num_pages }}{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">
        &raquo;</a>
    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}

students/templates/student_edit.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}Редагувати Студента{% endblock meta_title %}

{% block title %}Редагувати Студента{% endblock title %}

{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">Будь-ласка, виправте наступні помилки</div>
{% endif %}
{% endblock %}

{% block content %}

{% crispy form %}

{% endblock content %}